package com.example.projectclicnt.Model.GetData

import com.google.gson.annotations.SerializedName


data class Shop (

    @SerializedName("id"                             ) var id                             : String?    = null,
    @SerializedName("name"                           ) var name                           : String?    = null,
    @SerializedName("description"                    ) var description                    : String?    = null,
    @SerializedName("type"                           ) var type                           : String?    = null,
    @SerializedName("businessTypeId"                 ) var businessTypeId                 : String?    = null,
    @SerializedName("businessOperationType"          ) var businessOperationType          : String?    = null,
    @SerializedName("logo"                           ) var logo                           : String?    = null,
    @SerializedName("banner"                         ) var banner                         : String?    = null,
    @SerializedName("city"                           ) var city                           : String?    = null,
    @SerializedName("address"                        ) var address                        : String?    = null,
    @SerializedName("country"                        ) var country                        : String?    = null,
    @SerializedName("mobileNumber"                   ) var mobileNumber                   : String?    = null,
    @SerializedName("contactNumber"                  ) var contactNumber                  : String?    = null,
    @SerializedName("area"                           ) var area                           : String?    = null,
    @SerializedName("email"                          ) var email                          : String?    = null,
    @SerializedName("ownerId"                        ) var ownerId                        : String?    = null,
    @SerializedName("merchants"                      ) var merchants                      : String?    = null,
    @SerializedName("merchantIds"                    ) var merchantIds                    : String?    = null,
    @SerializedName("bankInfo"                       ) var bankInfo                       : String?    = null,
    @SerializedName("shopBrand"                      ) var shopBrand                      : String?    = null,
    @SerializedName("merchantBusinessAndContactInfo" ) var merchantBusinessAndContactInfo : String?    = null,
    @SerializedName("merchantBusinessInfo"           ) var merchantBusinessInfo           : String?    = null,
    @SerializedName("personalDetails"                ) var personalDetails                : String?    = null,
    @SerializedName("mobileBankService"              ) var mobileBankService              : String?    = null,
    @SerializedName("status"                         ) var status                         : String?    = null,
    @SerializedName("location"                       ) var location                       : Location?  = Location(),
    @SerializedName("slug"                           ) var slug                           : String?    = null,
    @SerializedName("createdAt"                      ) var createdAt                      : String?    = null,
    @SerializedName("updatedAt"                      ) var updatedAt                      : String?    = null,
    @SerializedName("createdBy"                      ) var createdBy                      : CreatedBy? = CreatedBy(),
    @SerializedName("updatedBy"                      ) var updatedBy                      : UpdatedBy? = UpdatedBy(),
    @SerializedName("prepareTime"                    ) var prepareTime                    : Int?       = null,
    @SerializedName("baseDeliveryCharge"             ) var baseDeliveryCharge             : Int?       = null,
    @SerializedName("isFreeDelivery"                 ) var isFreeDelivery                 : Boolean?   = null,
    @SerializedName("rating"                         ) var rating                         : Int?       = null,
    @SerializedName("numberOfRating"                 ) var numberOfRating                 : Int?       = null,
    @SerializedName("deleted"                        ) var deleted                        : Boolean?   = null,
    @SerializedName("keywords"                       ) var keywords                       : String?    = null,
    @SerializedName("vat"                            ) var vat                            : String?    = null,
    @SerializedName("minimumAmountForFreeDelivery"   ) var minimumAmountForFreeDelivery   : Int?       = null,
    @SerializedName("versionCode"                    ) var versionCode                    : String?    = null,
    @SerializedName("hubId"                          ) var hubId                          : String?    = null,
    @SerializedName("hub"                            ) var hub                            : String?    = null,
    @SerializedName("merchant"                       ) var merchant                       : String?    = null,
    @SerializedName("merchantId"                     ) var merchantId                     : String?    = null,
    @SerializedName("isActive"                       ) var isActive                       : Boolean?   = null,
    @SerializedName("displayOrder"                   ) var displayOrder                   : Int?       = null,
    @SerializedName("numberOfFollowers"              ) var numberOfFollowers              : Int?       = null,
    @SerializedName("isVerified"                     ) var isVerified                     : String?    = null,
    @SerializedName("commissionType"                 ) var commissionType                 : String?    = null,
    @SerializedName("commissionAmount"               ) var commissionAmount               : String?    = null,
    @SerializedName("subsidy"                        ) var subsidy                        : String?    = null,
    @SerializedName("minimumWithdrawalAmount"        ) var minimumWithdrawalAmount        : String?    = null,
    @SerializedName("startAt"                        ) var startAt                        : String?    = null,
    @SerializedName("endAt"                          ) var endAt                          : String?    = null,
    @SerializedName("orderCount"                     ) var orderCount                     : Int?       = null,
    @SerializedName("dineIn"                         ) var dineIn                         : String?    = null,
    @SerializedName("pickUp"                         ) var pickUp                         : String?    = null,
    @SerializedName("closeCause"                     ) var closeCause                     : String?    = null,
    @SerializedName("promo"                          ) var promo                          : String?    = null,
    @SerializedName("promoDescription"               ) var promoDescription               : String?    = null,
    @SerializedName("flashDiscount"                  ) var flashDiscount                  : String?    = null,
    @SerializedName("metaTitle"                      ) var metaTitle                      : String?    = null,
    @SerializedName("metaDescription"                ) var metaDescription                : String?    = null,
    @SerializedName("keyWord"                        ) var keyWord                        : String?    = null,
    @SerializedName("serviceFee"                     ) var serviceFee                     : String?    = null,
    @SerializedName("resellerCommissionType"         ) var resellerCommissionType         : String?    = null,
    @SerializedName("resellerCommissionAmount"       ) var resellerCommissionAmount       : String?    = null,
    @SerializedName("balance"                        ) var balance                        : String?    = null,
    @SerializedName("locationObj"                    ) var locationObj                    : String?    = null,
    @SerializedName("products"                       ) var products                       : String?    = null,
    @SerializedName("distance"                       ) var distance                       : String?    = null,
    @SerializedName("deliveryCharge"                 ) var deliveryCharge                 : String?    = null,
    @SerializedName("timeRemaining"                  ) var timeRemaining                  : String?    = null,
    @SerializedName("totalProducts"                  ) var totalProducts                  : String?    = null,
    @SerializedName("totalOrders"                    ) var totalOrders                    : String?    = null,
    @SerializedName("deliveryFullFillType"           ) var deliveryFullFillType           : String?    = null,
    @SerializedName("deliveryPackagingFullFillType"  ) var deliveryPackagingFullFillType  : String?    = null

)