package com.example.example

import com.example.apusing.Model.Campaign
import com.google.gson.annotations.SerializedName


data class Products (

  @SerializedName("id"                        ) var id                        : String?               = null,
  @SerializedName("name"                      ) var name                      : String?               = null,
  @SerializedName("type"                      ) var type                      : String?               = null,
  @SerializedName("slug"                      ) var slug                      : String?               = null,
  @SerializedName("productImage"              ) var productImage              : String?               = null,
  @SerializedName("rating"                    ) var rating                    : Int?                  = null,
  @SerializedName("numberOfRating"            ) var numberOfRating            : Int?                  = null,
  @SerializedName("isPopular"                 ) var isPopular                 : Boolean?              = null,
  @SerializedName("variations"                ) var variations                : ArrayList<Variations> = arrayListOf(),
  @SerializedName("deleted"                   ) var deleted                   : Boolean?              = null,
  @SerializedName("shop"                      ) var shop                      : Shop?                 = Shop(),
  @SerializedName("shopId"                    ) var shopId                    : String?               = null,
  @SerializedName("campaignId"                ) var campaignId                : String?               = null,
  @SerializedName("campaign"                  ) var campaign                  : Campaign?             = Campaign(),
  @SerializedName("barCode"                   ) var barCode                   : String?               = null,
  @SerializedName("hub"                       ) var hub                       : String?               = null,
  @SerializedName("hubId"                     ) var hubId                     : String?               = null,
  @SerializedName("category"                  ) var category                  : Category?             = Category(),
  @SerializedName("isActive"                  ) var isActive                  : Boolean?              = null,
  @SerializedName("bookingEnabled"            ) var bookingEnabled            : String?               = null,
  @SerializedName("addOns"                    ) var addOns                    : String?               = null,
  @SerializedName("metaTitle"                 ) var metaTitle                 : String?               = null,
  @SerializedName("metaDescription"           ) var metaDescription           : String?               = null,
  @SerializedName("brand"                     ) var brand                     : String?               = null,
  @SerializedName("stock"                     ) var stock                     : Int?                  = null,
  @SerializedName("isReturnable"              ) var isReturnable              : String?               = null,
  @SerializedName("excludeCOD"                ) var excludeCOD                : String?               = null,
  @SerializedName("status"                    ) var status                    : String?               = null,
  @SerializedName("approvedBy"                ) var approvedBy                : String?               = null,
  @SerializedName("updatedLogs"               ) var updatedLogs               : String?               = null,
  @SerializedName("createdAt"                 ) var createdAt                 : String?               = null,
  @SerializedName("updatedAt"                 ) var updatedAt                 : String?               = null,
  @SerializedName("createdBy"                 ) var createdBy                 : CreatedBy?            = CreatedBy(),
  @SerializedName("updatedBy"                 ) var updatedBy                 : UpdatedBy?            = UpdatedBy(),
  @SerializedName("description"               ) var description               : String?               = null,
  @SerializedName("salesCount"                ) var salesCount                : String?               = null,
  @SerializedName("visitors"                  ) var visitors                  : String?               = null,
  @SerializedName("productOrigin"             ) var productOrigin             : String?               = null,
  @SerializedName("displayOrder"              ) var displayOrder              : String?               = null,
  @SerializedName("isPreOrder"                ) var isPreOrder                : String?               = null,
  @SerializedName("prePaidAmountInPercentage" ) var prePaidAmountInPercentage : String?               = null,
  @SerializedName("paymentTimeInSeconds"      ) var paymentTimeInSeconds      : String?               = null,
  @SerializedName("imageAltrText"             ) var imageAltrText             : String?               = null,
  @SerializedName("imageTitle"                ) var imageTitle                : String?               = null,
  @SerializedName("imageDescription"          ) var imageDescription          : String?               = null,
  @SerializedName("imageCaption"              ) var imageCaption              : String?               = null,
  @SerializedName("canonicalTag"              ) var canonicalTag              : String?               = null,
  @SerializedName("groupBuyTotalGroups"       ) var groupBuyTotalGroups       : String?               = null,
  @SerializedName("groupBuyTotalParticipants" ) var groupBuyTotalParticipants : String?               = null,
  @SerializedName("campaignVariations"        ) var campaignVariations        : String?               = null,
  @SerializedName("noOfParticipatorEachGroup" ) var noOfParticipatorEachGroup : String?               = null,
  @SerializedName("isFreeDelivery"            ) var isFreeDelivery            : String?               = null,
  @SerializedName("breadcrumbs"               ) var breadcrumbs               : String?               = null,
  @SerializedName("productSource"             ) var productSource             : String?               = null,
  @SerializedName("isResellAllowed"           ) var isResellAllowed           : String?               = null,
  @SerializedName("isResellerProduct"         ) var isResellerProduct         : String?               = null,
  @SerializedName("accessories"               ) var accessories               : String?               = null,
  @SerializedName("productType"               ) var productType               : String?               = null,
  @SerializedName("auction"                   ) var auction                   : String?               = null,
  @SerializedName("productCondition"          ) var productCondition          : String?               = null

)